spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hr_management
    username: postgres
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: ecetasci.iu@gmail.com
    password: czob jkfr xjoh ofal
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

app:
  jwtSecret: ${JWT_SECRET}
  file:
    upload-dir: uploads/expenses

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
